name = "Poultry Apocalypse"
author = "AMTraxTGE"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b54aefbdf010be2dade78459a1db5e49685e2dd4ed5f63d638eaff295053b32"

[versions]
fabric = "0.16.13"
minecraft = "1.21.1"
