name = "Poultry Apocalypse"
author = "AMTraxTGE"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff82c086b460361b506f897e2251751cda218217effe16616fdbbf66844c2d54"

[versions]
fabric = "0.16.13"
minecraft = "1.21.1"
