name = "Poultry Apocalypse"
author = "AMTraxTGE"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af698bf5ad1a3d73433250b2db4468bc2eb3d3dfb9d06964f18a359d18086b6c"

[versions]
fabric = "0.16.13"
minecraft = "1.21.1"
