name = "Poultry Apocalypse"
author = "AMTraxTGE"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62bc6930d16218023dc1c83c961c26015d2708d683f298229a104eb71c6740c7"

[versions]
fabric = "0.16.13"
minecraft = "1.21.1"
