name = "Poultry Apocalypse"
author = "AMTraxTGE"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b860624280f8aac3fc02a53b91cfa2b46fdb56035aa03b2fba58fad4b88b64d6"

[versions]
fabric = "0.16.13"
minecraft = "1.21.1"
